/*The reporting queries */

/*1.Select all duties that have been set in the current month and display the details of their 
assigned staff and volunteer*/
SELECT DUTIES.DATE_SET, DUTIES.DUTY_TASK, DUTIES.DOG_NAME, STAFF.STAFF_ID, STAFF.FIRSTNAME, STAFF.LASTNAME, 
VOLUNTEERS.VOLUNTEER_NIK, VOLUNTEERS.FIRSTNAME, VOLUNTEERS.LASTNAME
FROM ((DUTIES
INNER JOIN STAFF ON DUTIES.STAFF_ID = STAFF.STAFF_ID)
INNER JOIN VOLUNTEERS ON DUTIES.VOLUNTEER_NIK = VOLUNTEERS.VOLUNTEER_NIK)
WHERE DATE_SET BETWEEN '2018-10-05' AND '2018-11-05'
ORDER BY DATE_SET


/* 2.Update Duty task with new DUE date and new staff.*/
UPDATE DUTIES
SET DATE_DUE = '2018-12-24'
WHERE DUTY_TASK = 'Grooming';

UPDATE DUTIES
SET STAFF_ID = 'C0005'
WHERE DUTY_TASK = 'Grooming';


/*3.Display different cities for Staff and Volunteers.*/
SELECT CITY FROM STAFF
UNION
SELECT CITY FROM VOLUNTEERS
ORDER BY CITY;

/*4.Display all Staff and Volunteers who have recently joined the Organisation.*/
SELECT START_DATE, FIRSTNAME, LASTNAME FROM STAFF
WHERE START_DATE BETWEEN '2016-11-05' AND '2018-11-05'
UNION
SELECT START_DATE, FIRSTNAME, LASTNAME FROM VOLUNTEERS
WHERE START_DATE BETWEEN '2016-11-05' AND '2018-11-05'
ORDER BY START_DATE;


/*5.List the number of dogs by Size (S, M, L).*/
SELECT COUNT(DOG_NAME), SIZE
FROM DOGS
GROUP BY SIZE
ORDER BY COUNT(DOG_NAME) DESC;


/*6.Display the details of dogs from a specific breed.*/
SELECT DOGS.DOG_NAME, DOGS.SEX, DOGS.SIZE, DOGS.KENNEL_NUMBER, DOGS.STAFF_ID, STAFF.FIRSTNAME, STAFF.LASTNAME
FROM DOGS
INNER JOIN STAFF ON DOGS.STAFF_ID = STAFF.STAFF_ID
WHERE BREED LIKE '%mastiff%'
ORDER BY DOG_NAME;

/*2. List all volunteers born in between certain dates*/
SELECT DOB, VOLUNTEER_NIK, LASTNAME
FROM VOLUNTEERS
WHERE DOB BETWEEN '1998-11-05' AND '2000-11-05'
ORDER BY DOB;


/*3.Count total number of Dogs born in a specific Year*/
SELECT DOB, DOG_NAME, SEX
FROM DOGS
WHERE DOB LIKE '%2017%'
ORDER BY DOB;
